name: bitwarden_backup_decryptor
description: CLI tool to decrypt backup files exported from Bitwarden
version: 0.0.1
repository: https://github.com/elliotwutingfeng/bitwarden_backup_decryptor
funding:
  - https://www.buymeacoffee.com/elliotwutingfeng
topics:
  - crypto
  - cryptography
  - encryption
  - security

publish_to: 'none'

environment:
  sdk: ^3.11.0

dependencies:
  cipherlib: ^0.7.2
  convert: ^3.1.2

dev_dependencies:
  coverage: ^1.15.1
  lints: ^6.1.0
  mocktail: ^1.0.5
  test: ^1.32.0
